services:
  db:
    image: "postgres:18.0-bookworm"
    env_file:
      - .env
    ports:
      - "${PGPORT}:${PGPORT}"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 3s
      timeout: 3s
      retries: 3
    volumes:
      - ./data:/var/lib/postgresql/18/docker
    profiles:
      - "dev"
      - "prod"

  seaweedfs-master:
    image: chrislusf/seaweedfs:latest
    command: "master -ip=seaweedfs-master -ip.bind=0.0.0.0 -port=${SEAWEEDFS_MASTER_PORT} -mdir=/data"
    ports:
      - "${SEAWEEDFS_MASTER_PORT}:${SEAWEEDFS_MASTER_PORT}"
    volumes:
      - seaweedfs-master-data:/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${SEAWEEDFS_MASTER_PORT}/cluster/status"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    profiles:
      - "dev"
      - "prod"

  seaweedfs-volume:
    image: chrislusf/seaweedfs:latest
    command: "volume -mserver=seaweedfs-master:${SEAWEEDFS_MASTER_PORT} -ip=seaweedfs-volume -ip.bind=0.0.0.0 -port=${SEAWEEDFS_VOLUME_PORT} -max=100 -dir=/data"
    ports:
      - "${SEAWEEDFS_VOLUME_PORT}:${SEAWEEDFS_VOLUME_PORT}"
    volumes:
      - seaweedfs-volume-data:/data
    depends_on:
      seaweedfs-master:
        condition: service_healthy
    profiles:
      - "dev"
      - "prod"

  app:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    depends_on:
      db:
        condition: service_healthy
      seaweedfs-master:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./src
        target: /usr/local/app/src
    ports:
      - "${FRONTEND_PORT}:3000"
    profiles:
      - "dev"

  app-prod:
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    depends_on:
      db:
        condition: service_healthy
      seaweedfs-master:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:3000"
    profiles:
      - "prod"

volumes:
  seaweedfs-master-data:
  seaweedfs-volume-data: